apiVersion: v1
kind: Service
metadata:
  name: ipfs
  namespace: b3
  labels:
    k8s-app: ipfs
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - name: tcp-4001-4001-dl4v6
      protocol: TCP
      port: 4001
      targetPort: 4001
  selector:
    k8s-app: ipfs
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster